### PR TITLE
using defer(underscore.js) for prevent block event, and transaction more efficient

### PR DESCRIPTION
**Pull request by gimdongwoo**

### CODE REVIEW

**Comment by viezel** [comment]
looks good. please bump the version and update the changelog in readme.

**Comment by gimdongwoo** [comment]
It's done. It is my honor. Thank you.

**Comment by viezel** [comment]
perfect!

**Comment by HazemKhaled** [comment]
This is the where we really need to use _.defer

Thanks a lot

**Comment by yomybaby** [comment]
:+1:

**Pull request merged**
