### PR TITLE
readSQL : JSON.parse added for stringified object

### PR DESCRIPTION
**Pull request by gimdongwoo**
readSQL : JSON.parse added for stringified object

Thanks you!!

### CODE REVIEW

**Comment by viezel** [comment]
I cannot accept that. It has a mayor performance hit.

**Comment by gimdongwoo** [comment]
Thanks for your advise.

So, for check json obeject using regexp.

Thank you.

**Comment by gimdongwoo** [comment]
I removed my temporary loger code.

**Comment by gimdongwoo** [comment]
Before commit have some bug fix.

Sorry.

**Comment by viezel** [comment]
We cannot have that in the core.. think if this was 50.000 items that should go through that if statement. 
it will be way too slow.

**Pull request closed without merging**
