### PR TITLE
HTTP RFC2616 If-Modified-Since support

### PR DESCRIPTION
**Pull request by jvandijk**
This PR is meant to deliver proper support for API's implementing the RFC 2616 If-Modified-Since support.
It separated into 2 commits:
- one to do minor clean ups on trailing whitespace and missing braces, 
- the other for the physical change in modified since implementation.

Important note: This IS a BC break to the current last-modified implementation, but it's for the greater good in my opinion because the current situation is incorrect. Last-Modified is the header which is send in the response, not in the request.

Looking forward to your feedback!

### CODE REVIEW

**Comment by viezel** [comment]
Hi @jvandijk 
Thanks for taking the time to create this. First of all nice work. 
You are so right regarding the "Last-Modified". That should not be there (my bad). But to my understanding the correct implementation would be "If-None-Match" since we are checking for the ETag header. 

     On a subsequent GET request you can put the value in that ETag: header in an 
     If-None-Match: header and if there is a representation that has that etag, i.e. 
     if the representation hasn't changed, then the response is a 304 with no entity body returned.

Source: http://bitworking.org/news/150/REST-Tip-Deep-etags-give-you-more-benefits

So I think we could use both headers. Maybe it make sence to make a adapter config setting for this. So developers can choose with header they want. 
I would suggest that the "If-None-Match" would be the default.

**Comment by jvandijk** [comment]
I understand your point of view from an entity perspective, but using ETag - If-None-Match communication in case of collections / listing is always a bit harder to implement on the server side. In case of i.e. news items there always is an item that has the last modification time. If exactly that news item doesn't meet the filters set by a requesting client, why would I update the data on the client? How would you do that with Etags?

**Comment by viezel** [comment]
How to implement:
We use Laravel Framework (PHP) for all our API development, and its has a quite easy way to implement  If-None-Match. It just a simple check if match exists, the return not modified. Else return the item(s). 

        $newETag = Request::getEtag();
        if ( isset($newETag) && $newETag === $currentETag ) {
            return $this->responseNotModified(['ETag' => $currentETag]);
        }

But again - I think both solutions would be valid for a rest adapter. Hence we should extend it to have both opportunities.

**Comment by jvandijk** [comment]
Wow! I assume tested and agreed? I will send another PR to update the documentation....

**Pull request merged**
